name: ci
on:
  push:
    branches:[ main,master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pytest 
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Run pytest
        run: |
          export PYTHONPATH="$GITHUB_WORKSPACE:$PYTHONPATH"  # so your package-less code imports
          pytest

